# Generated by Django 3.2.16 on 2022-11-12 01:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_teachers'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='people',
            name='name',
        ),
        migrations.RemoveField(
            model_name='people',
            name='password',
        ),
    ]
