# Generated by Django 3.2.16 on 2022-11-12 01:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_alter_people_klass'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='people',
            name='klass',
        ),
        migrations.AddField(
            model_name='people',
            name='studentclass',
            field=models.CharField(choices=[('P1', 'P1'), ('P2', 'P2'), ('P3', 'P3'), ('P4', 'P4'), ('P5', 'P5'), ('P6', 'P6'), ('P7', 'P7')], default='P1', max_length=2),
        ),
    ]
