# Generated by Django 3.2.16 on 2022-11-12 06:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_auto_20221112_0149'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='people',
            name='name',
        ),
        migrations.AddField(
            model_name='people',
            name='emergencyname',
            field=models.CharField(default='mother mary', max_length=100),
        ),
        migrations.AddField(
            model_name='people',
            name='emergencyno',
            field=models.IntegerField(default=911, max_length=30),
        ),
        migrations.AddField(
            model_name='people',
            name='fathersname',
            field=models.CharField(default='dad name', max_length=100),
        ),
        migrations.AddField(
            model_name='people',
            name='fathersnumber',
            field=models.IntegerField(default=200000001, max_length=30),
        ),
        migrations.AddField(
            model_name='people',
            name='firstname',
            field=models.CharField(default='fname', max_length=100),
        ),
        migrations.AddField(
            model_name='people',
            name='mothersname',
            field=models.CharField(default='mom name', max_length=100),
        ),
        migrations.AddField(
            model_name='people',
            name='mothersnumber',
            field=models.IntegerField(default=10000001, max_length=30),
        ),
        migrations.AddField(
            model_name='people',
            name='parentemail',
            field=models.CharField(default='test@gmail.com', max_length=100),
        ),
        migrations.AddField(
            model_name='people',
            name='secondname',
            field=models.CharField(default='sname', max_length=100),
        ),
        migrations.AddField(
            model_name='people',
            name='studentgender',
            field=models.CharField(choices=[('B', 'Boy'), ('G', 'Girl'), ('N', 'None')], default='N', max_length=1),
        ),
        migrations.AlterField(
            model_name='people',
            name='password',
            field=models.CharField(default='testpass', max_length=100),
        ),
    ]
