# Generated by Django 3.2.16 on 2022-11-12 06:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0008_auto_20221112_0606'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='People',
            new_name='Students',
        ),
    ]
