# Generated by Django 3.2.16 on 2022-11-12 07:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0009_rename_people_students'),
    ]

    operations = [
        migrations.AddField(
            model_name='students',
            name='studentbirth',
            field=models.DateField(default='1990-01-01'),
        ),
    ]
