# Generated by Django 3.2.16 on 2022-11-13 03:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0011_auto_20221112_1933'),
    ]

    operations = [
        migrations.AlterField(
            model_name='teachers',
            name='title',
            field=models.CharField(choices=[('Mr', 'Mr'), ('Mrs', 'Mrs'), ('Miss', 'Miss')], max_length=5),
        ),
    ]
