# Generated by Django 3.2.16 on 2022-12-11 23:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0012_alter_teachers_title'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserRoles',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rname', models.CharField(default='', max_length=100)),
                ('role', models.CharField(choices=[('teacher', 'teacher'), ('admin', 'admin'), ('student', 'student'), ('support', 'support')], max_length=20)),
                ('password', models.CharField(default='', max_length=100)),
            ],
            options={
                'ordering': ('rname',),
            },
        ),
    ]
