# Generated by Django 3.2.16 on 2022-12-12 20:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0013_userroles'),
    ]

    operations = [
        migrations.CreateModel(
            name='PresentStudents',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('firstname', models.CharField(max_length=100)),
                ('secondname', models.CharField(max_length=100)),
                ('isPresent', models.CharField(choices=[('true', 'true'), ('false', 'false')], max_length=20)),
                ('sid', models.CharField(max_length=100)),
            ],
            options={
                'ordering': ('firstname',),
            },
        ),
    ]
