# Generated by Django 3.2.16 on 2022-12-12 20:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0015_presentstudents_studentclass'),
    ]

    operations = [
        migrations.AddField(
            model_name='presentstudents',
            name='classdate',
            field=models.DateField(default='1987-01-01'),
        ),
        migrations.AddField(
            model_name='presentstudents',
            name='studentsubject',
            field=models.CharField(default='Art', max_length=100),
        ),
        migrations.AlterField(
            model_name='presentstudents',
            name='isPresent',
            field=models.CharField(choices=[('true', 'true'), ('false', 'false')], default='false', max_length=20),
        ),
    ]
