# Generated by Django 3.2.16 on 2022-12-12 20:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0022_remove_presentstudents_classdate'),
    ]

    operations = [
        migrations.CreateModel(
            name='PresentStudent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('classdate', models.DateField()),
                ('firstname', models.CharField(max_length=100)),
                ('secondname', models.CharField(max_length=100)),
                ('isPresent', models.CharField(choices=[('true', 'true'), ('false', 'false')], default='false', max_length=20)),
                ('sid', models.CharField(max_length=100)),
                ('studentsubject', models.CharField(default='Art', max_length=100)),
                ('studentclass', models.CharField(choices=[('P1', 'P1'), ('P2', 'P2'), ('P3', 'P3'), ('P4', 'P4'), ('P5', 'P5'), ('P6', 'P6'), ('P7', 'P7')], default='P1', max_length=2)),
            ],
            options={
                'ordering': ('firstname',),
            },
        ),
        migrations.DeleteModel(
            name='PresentStudents',
        ),
    ]
