# Generated by Django 3.2.16 on 2022-12-22 10:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0023_auto_20221212_2044'),
    ]

    operations = [
        migrations.AlterField(
            model_name='presentstudent',
            name='classdate',
            field=models.CharField(default=0, max_length=50),
        ),
    ]
