# Generated by Django 3.2.16 on 2023-01-10 13:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0024_alter_presentstudent_classdate'),
    ]

    operations = [
        migrations.CreateModel(
            name='PresentStudent2',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('currentdate', models.CharField(default=0, max_length=50)),
                ('firstname', models.CharField(max_length=100)),
                ('secondname', models.CharField(max_length=100)),
                ('presentstatus', models.CharField(choices=[('true', 'true'), ('false', 'false')], default='false', max_length=20)),
                ('sid', models.CharField(max_length=100)),
                ('studentclass', models.CharField(choices=[('P1', 'P1'), ('P2', 'P2'), ('P3', 'P3'), ('P4', 'P4'), ('P5', 'P5'), ('P6', 'P6'), ('P7', 'P7')], default='P1', max_length=2)),
            ],
            options={
                'ordering': ('id',),
            },
        ),
        migrations.CreateModel(
            name='TimeTable',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('classTime', models.CharField(default=0, max_length=50)),
                ('classDay', models.CharField(choices=[('monday', 'monday'), ('tuesday', 'tuesday'), ('wednesday', 'wednesday'), ('thursday', 'thursday'), ('friday', 'friday')], max_length=100)),
                ('subject', models.CharField(max_length=100)),
            ],
            options={
                'ordering': ('classDay',),
            },
        ),
        migrations.AlterModelOptions(
            name='presentstudent',
            options={'ordering': ('-id',)},
        ),
    ]
