# Generated by Django 3.2.16 on 2023-01-11 13:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0026_timetable_studentclass'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='timetable',
            options={'ordering': ('classTime',)},
        ),
    ]
