# Generated by Django 3.2.16 on 2023-02-23 03:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0028_subjects'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subjects',
            name='subjectName',
            field=models.CharField(max_length=50, unique=True),
        ),
    ]
