# Generated by Django 3.2.16 on 2023-02-23 03:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0029_alter_subjects_subjectname'),
    ]

    operations = [
        migrations.AddField(
            model_name='subjects',
            name='subjectInfo',
            field=models.CharField(max_length=200, null=True),
        ),
    ]
