# Generated by Django 3.2.16 on 2023-02-23 19:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0030_subjects_subjectinfo'),
    ]

    operations = [
        migrations.CreateModel(
            name='SubjectTeacher',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subjectName', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.subjects')),
                ('subjectTeacher', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.teachers')),
            ],
        ),
    ]
