# Generated by Django 3.2.16 on 2023-02-23 21:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0032_auto_20230223_2009'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subjectteacher',
            name='subjectName',
            field=models.ForeignKey(db_column='subjectName', on_delete=django.db.models.deletion.CASCADE, to='api.subjects', verbose_name='subjectName'),
        ),
    ]
